name: Automatic Changelog

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        npm install -g auto-changelog
    - name: Generate changelog
      run: |
        npm run version
        git push origin HEAD:master
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CI: true
